# Generated by Django 2.1.10 on 2019-11-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asociación',
                'verbose_name_plural': 'Asociaciones',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Relación',
                'verbose_name_plural': 'Relaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'Espacio de trabajo', 'verbose_name_plural': 'Espacios de trabajo'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='graph',
        ),
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='graph.WorkSpace', verbose_name='Espacio de trabajo'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Espacio de trabajo'),
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.AddField(
            model_name='association',
            name='entity_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_1', to='graph.Entity', verbose_name='Entidad 1'),
        ),
        migrations.AddField(
            model_name='association',
            name='entity_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_2', to='graph.Entity', verbose_name='Entidad 2'),
        ),
        migrations.AddField(
            model_name='association',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='graph.Relationship', verbose_name='Relación'),
        ),
        migrations.AddField(
            model_name='association',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='graph.WorkSpace', verbose_name='Espacio de trabajo'),
        ),
    ]
